### ISSUE TITLE
Running with local/remote bitcoind

### ISSUE THREAD

**Issue by jatinstack** [1200wd/blocksmurfer#2]
Hi, want to use this service with my own bitcoind server that I have running, however you're using Service class from bitcoinlib which is default for service providers, Bitcoind class is there to connect to local node.

Can you suggest how can I connect to my node and get balance for addresses.

**Comment by mccwdev** [comment]
See https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.setup-bitcoind-connection.html

If you want to query addresses you have to add them to the bitcoiind wallet first.
